### ISSUE TITLE
Empty stations outside of SR

### ISSUE THREAD

**Issue by mrshu** [errbotters/err-sktravel#4]
I ran into this today:

```
!vlak ba brno
[Vlak] Bratislava hl.st.  4:25 -> Kúty  5:30 >> [Vlak] Kúty  6:04 ->   6:23 >> [Vlak]   6:40 ->   7:24 (2 hod 59 min, 141 km)
```

I am not sure how involved would the fix be or whether this repository is the right one for this issue but I believe it should not be difficult to fix.

**Comment by Adman** [comment]
@mrshu the fix has to be done on cpsk api side

**Comment by mrshu** [comment]
@Adman fair enough, feel free to move it there then. I am not sure how to reproduce it using just the cpsk API.

**Comment by Adman** [comment]
@mrshu There's the `test.py` file ;-)

**Comment by Adman** [comment]
@mrshu The bug appears when `<td>` is not the leaf node of city name

**Comment by Adman** [comment]
@mrshu fixed https://github.com/Adman/python-cpsk-api/commit/b383c8ebdc421be73055bc47f02e5b2303aee72d
